### ISSUE TITLE
Ruby 2.2 ERROR: Failed to build gem native extension

### ISSUE THREAD

**Issue by Ch4s3** [louismullie/treat#91] opened 2015-01-15 19:14 UTC
I get the following tring to install with Ruby 2.2.

```
  ERROR:  Error installing treat:
    ERROR: Failed to build gem native extension.

      /Users/chase/.rvm/rubies/ruby-2.2.0/bin/ruby -r ./siteconf20150115-38059-17qul84.rb extconf.rb
  creating Makefile

  make "DESTDIR=" clean

  make "DESTDIR="
  compiling native.c
  native.c:39:8: warning: unused variable 'node_a' [-Wunused-variable]
          VALUE node_a;
                ^
  native.c:40:8: warning: unused variable 'node_b' [-Wunused-variable]
          VALUE node_b;
                ^
  native.c:41:8: warning: unused variable 'directed' [-Wunused-variable]
          VALUE directed;
                ^
  native.c:42:8: warning: unused variable 'direction' [-Wunused-variable]
          VALUE direction;
                ^
  native.c:58:1: warning: control may reach end of non-void function [-Wreturn-type]
  }
  ^
  native.c:272:8: warning: implicit declaration of function 'RHASH' is invalid in C99 [-Wimplicit-function-declaration]
    if (!RHASH(features)->ntbl) {
         ^
  native.c:272:25: error: member reference type 'int' is not a pointer
    if (!RHASH(features)->ntbl) {
         ~~~~~~~~~~~~~~~  ^
  6 warnings and 1 error generated.
  make: *** [native.o] Error 1

  make failed, exit code 2
```

**Comment by shawn42** [comment] 2015-01-28 12:31
I can confirm this error as well.
It looks like the hash internals changed in 2.2; these will need to conditionally be used:

#define RHASH_TBL(h) rb_hash_tbl(h)
#define RHASH_SIZE(h) NUM2SIZET(rb_hash_size(h))

instead of the RHASH(xxx)->ntbl calls.

**Comment by faustoct** [comment] 2015-03-12 18:33
I did a patch for that but is unofficial one. 
https://github.com/faustoct/birch/

More details in:
- birch gem describing this issue https://github.com/louismullie/birch/issues/11.
- Ruby hide internal hash: https://bugs.ruby-lang.org/issues/9889

**Comment by alexed1** [comment] 2015-04-06 19:19
would love to see a fix for this. can't use treat as a result. I was able eto build a treat gem using faustoct's fork, but I can't figure out how to get my 2.2 project to use that gem instead of trying to build a new one in the 2.2. world

**Comment by kylekyle** [comment] 2015-04-13 14:12
@faustoct: thanks for the birch fork. It saved the day.

**Comment by agarie** [comment] 2015-04-13 21:46
@alexed1 you can link to a specific git repository [via your Gemfile](http://bundler.io/git.html).

**Comment by louismullie** [comment] 2015-04-13 22:35
@faustoct Can you submit a PR for your fork to the main birch repository?

**Comment by faustoct** [comment] 2015-04-14 02:33
@louismullie  PR submitted

**Comment by Ch4s3** [comment] 2015-04-14 02:47
:+1:

**Comment by sepastian** [comment] 2015-04-23 08:18
:+1:

If you are using rbenv, you can also do:

    $ cd your_project
    $ rbenv local 2.1.5
    $ bundle

The build works in Ruby 2.1.x.

**Comment by wired00** [comment] 2015-05-10 09:50
Based on the details gleaned above, here are the exact steps I followed to get treat working with ruby 2.2 on osx yosemite

* gem install 'specific_install'
* gem specific_install -l https://github.com/faustoct/birch.git
* gem install 'treat'
* Then followed this: https://github.com/louismullie/treat/wiki/Manual#installing-treat-core
. which required from terminal:
  * # irb
  * # require 'treat'
  * # Treat::Core::Installer.install 'english'

**Comment by zibs** [comment] 2015-06-20 00:50
Thank you so much @wired00!

**Comment by ludoplex** [comment] 2015-06-22 00:45
![boy_1106034a](https://cloud.githubusercontent.com/assets/5705162/8274076/fffb89ee-1823-11e5-906d-40bd55d3fb5c.jpg)

@wired00! YOU ARE AWESOME!

**Comment by wired00** [comment] 2015-06-22 00:52
Glad it helped you guys! :)

**Comment by naltun** [comment] 2015-12-24 14:41
@wired00 I am running Ubuntu 14.04.2 and this worked perfectly. Cheers!! :+1:

**Comment by samueleaton** [comment] 2016-01-06 22:21
I'm getting this error too. It works when i add the fork from @faustoct to my Gemfile.

`gem 'birch', git: 'https://github.com/faustoct/birch/'`

**Comment by travispearl** [comment] 2016-09-13 14:44
For those still struggling with treat gem installation in Ruby - here is the workaround to modify your Gemfile:

**Gemfile**
#add birch gem installation first with path to faustoct version
gem "birch", :git => 'https://github.com/faustoct/birch.git'
gem "treat"

_Then 'bundle install' will work as expected_

**Comment by louismullie** [comment] 2017-04-22 20:07
Fixed in most recent birch release

**Closed by louismullie** 2017-04-22 20:07 UTC
