### ISSUE TITLE
Getting `WordNet::SynsetType not defined` 

### ISSUE THREAD

**Issue by aclinnovator** [louismullie/treat#97] opened 2015-03-12 01:51 UTC
First off, this library seems awesome! - I am going to use it to build a tweet responding bot - if I could only get it to work. 

Also, I run `Treat::Core::Installer.install` and `Treat::Core::Installer.install 'english'`

When trying to run the examples in `README`, I come across the error; `NameError: constant  WordNet::SynsetType not defined` when running `"hello".synonyms` and for other word related functions. Any ideas what's up with this, or what dependencies I haven't installed

**Comment by chickensmitten** [comment] 2015-03-14 08:27
Similar issue here. Could it be that the Java_home is not properly installed? there seems to be instructions in this blog post (http://www.sitepoint.com/seeking-lovecraft-part-1-an-introduction-to-nlp-and-the-treat-gem/), but I don't know how to get $JAVA_HOME environment variable configured properly. Any ideas?

**Comment by ojak** [comment] 2015-03-19 21:53
@aclinnovator Have you included the DSL?
```ruby
include Treat::Core::DSL
```

**Comment by trosborn** [comment] 2015-04-05 05:07
The issue is called by the most recent update to rwordnet. rwordnet 1.0.0 renames SynsetType. In order to get this working you can use rwordnet, 0.1.3 or older.

I tried renaming the constant to work with the latest version of rwordnet, but then I ran into a problem related to indices. I'll look into it more and some point.

**Comment by louismullie** [comment] 2015-04-10 19:23
Fixed by the PR above and subsequent PRs. Thanks!

**Closed by louismullie** 2015-04-10 19:23 UTC

**Comment by trosborn** [comment] 2015-04-10 21:02
You're welcome. I'm happy to lend a hand :smile:
